services:
  mongo:
    image: mongo:4.4
    restart: always
    ports:
      - 27020:27017
    environment:
      - MONGO_DATA_DIR=/data
    volumes:
      - ./docker/mongo:/data
  svelte:
    image: svelte-docker-dev
    build:
      context: .
      dockerfile: docker/node/Dockerfile
    ports:
      - 5173:5173
    volumes:
      - ./src/src:/app/src
      - ./src/static:/app/static
